#!/bin/sh

COLUMN=disk 	# Name of the column
COLOR=green		# By default, everything is OK

WARNING=40
CRITICAL=90
IGNORE_FS='^(tmpfs|devtmpfs|overlay|squashfs)$'

STATUS=0

DISKUSAGE=$(df -P -T | tail -n +2)

# Use input redirection instead of a pipe
while read -r FS TYPE SIZE USED AVAIL USEP MOUNT; do
    echo "$TYPE" | grep -Eq "$IGNORE_FS" && continue

    USE=${USEP%\%}

    if [ "$USE" -ge "$CRITICAL" ]; then
        #echo "CRITICAL: $MOUNT is at ${USE}% usage"
        STATUS=2
    elif [ "$USE" -ge "$WARNING" ] && [ "$STATUS" -lt 2 ]; then
        #echo "WARNING:  $MOUNT is at ${USE}% usage"
        STATUS=1
    fi
done <<EOF
echo -e "$DISKUSAGE"
EOF

# case "$STATUS" in
#     0)
#         echo "OK: All partitions are below ${WARNING}% usage"
#         ;;
#     1)
#         echo "WARNING: One or more partitions exceed ${WARNING}% usage"
#         ;;
#     2)
#         echo "CRITICAL: One or more partitions exceed ${CRITICAL}% usage"
#         ;;
# esac
#
# exit "$STATUS"

case "$STATUS" in
    0)
        COLOR=green
        MSG="OK: All partitions are below ${WARNING}% usage"
        ;;
    1)
        COLOR=yellow
        MSG="WARNING: One or more partitions exceed ${WARNING}% usage"
        ;;
    2)
        COLOR=red
        MSG="CRITICAL: One or more partitions exceed ${CRITICAL}% usage"
        ;;
esac

# echo "$COLUMN $COLOR $(date) $MSG"
printf '%s\n\n%s\n\n%s\n' "$COLUMN $COLOR $(date)" "$MSG" "$DISKUSAGE"

exit 0
