<TABLE SUMMARY="_font_size_1_Xymon_infrastructure_font Group Block" BORDER=0 CELLPADDING=2>
<TR>
  <!-- <TD ALIGN=CENTER VALIGN=BOTTOM WIDTH=45><FONT COLOR="#87a9e5" SIZE="-1"><B>host</B></FONT></TD> -->
  <TD ALIGN=CENTER VALIGN=BOTTOM WIDTH=45></TD>
{{{PROBES}}}
</TR>
<TR><TD COLSPAN=20><HR WIDTH="100%"></TD></TR>